default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: rorBlogDB
  password: inguarded7277
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test
